trigger:
- main

pool:
  Uipath

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: UiPathTest@4
  inputs:
    testTarget: 'TestSet'
    orchestratorConnection: 'Uipath'
    testSet: 'Charushila'
    folderName: 'Karan'

- task: UiPathTest@4
  inputs:
    testTarget: 'TestSet'
    orchestratorConnection: 'Uipath'
    testSet: 'Rajesh'
    folderName: 'Karan'

- task: UiPathTest@4
  inputs:
    testTarget: 'TestSet'
    orchestratorConnection: 'Uipath'
    testSet: 'Karan'
    folderName: 'Karan'

- task: UiPathTest@4
  inputs:
    testTarget: 'TestSet'
    orchestratorConnection: 'Uipath'
    testSet: 'Rachana'
    folderName: 'Karan'
